#!/usr/bin/python3

# PlatformIO pre-build script: generates build_info_gen.h (git hash, UTC build date,
# variant, env, board) in the build directory, for src/helpers/BuildInfo.cpp.
# It's written to the build directory, not the source tree, so it never makes the git tree
# dirty. Only files including it are recompiled when it changes.

import os
import re
import subprocess
from datetime import datetime, timezone

Import("env")


def git(*args):
    try:
        return subprocess.check_output(
            ["git", *args], cwd=env.subst("$PROJECT_DIR"), stderr=subprocess.DEVNULL
        ).decode().strip()
    except Exception:
        return ""


def find_variant():
    # the variant is the project's variants/<name> directory, given with -I in the build
    # flags (checked first), or on the include path. Framework variant directories (e.g.
    # the Arduino core's variants/esp32s3) are outside the project and ignored.
    project = env.subst("$PROJECT_DIR")
    pattern = r"variants[/\\]([^/\\\s\"']+)"
    for flag in env.Flatten(env.get("BUILD_FLAGS", [])):
        m = re.search(r"-I\s*\"?(\S*?)" + pattern, env.subst(str(flag)))
        if m and not os.path.isabs(m.group(1)):
            return m.group(2)
    for p in env.Flatten(env.get("CPPPATH", [])):
        path = env.subst(str(p))
        m = re.search(pattern, path)
        if m and os.path.abspath(path).startswith(os.path.abspath(project)):
            return m.group(1)
    return "unknown"


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


git_hash = git("rev-parse", "--short=7", "HEAD") or "unknown"
if git_hash != "unknown" and git("status", "--porcelain", "--untracked-files=no"):
    git_hash += "-dirty"

info = {
    "BUILD_GIT_HASH": git_hash,
    "BUILD_DATE_UTC": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "BUILD_VARIANT": find_variant(),
    "BUILD_ENV": env.subst("$PIOENV"),
    "BUILD_BOARD": env.BoardConfig().id,
}

out_dir = os.path.join(env.subst("$BUILD_DIR"), "build_info")
os.makedirs(out_dir, exist_ok=True)
header = "// generated by build_info.py - do not edit\n#pragma once\n" + "".join(
    "#define %s %s\n" % (k, c_str(v)) for k, v in info.items()
)
path = os.path.join(out_dir, "build_info_gen.h")
old = open(path).read() if os.path.exists(path) else None
if old != header:
    with open(path, "w") as f:
        f.write(header)

env.Append(CPPPATH=[out_dir])
print("build_info: git %s, built %s, variant %s, env %s, board %s" % (
    info["BUILD_GIT_HASH"], info["BUILD_DATE_UTC"], info["BUILD_VARIANT"], info["BUILD_ENV"], info["BUILD_BOARD"]))
